### ISSUE TITLE
Error in eigen(K, symmetric = TRUE) : 0 x 0 matrix

### ISSUE THREAD

**Issue by igm11-aa** [xiaolei-lab/rMVP#102]
Dear rMVP community,

I got this error message when try to run MVP.Data function:
Error in eigen(K, symmetric = TRUE) : 0 x 0 matrix
In addition: Warning messages:
1: In MVP.Data(fileHMP = "Ganoderma.5k.hmp.txt", filePhe = "GanodermaGWAS.Pheno.txt",  :
  SNP.effect has been DEPRECATED.
2: In MVP.Data(fileHMP = "Ganoderma.5k.hmp.txt", filePhe = "GanodermaGWAS.Pheno.txt",  :
  sep.hmp has been DEPRECATED.

MVP.Data(fileHMP="Ganoderma.5k.hmp.txt",
         filePhe="GanodermaGWAS.Pheno.txt",
         sep.hmp="\t",
         sep.phe="\t",
         SNP.effect="Add",
         fileKin=TRUE,
         filePC=TRUE,
         #priority="memory",
         #maxLine=10000,
         out="mvp.hmp"
)

I assure there is no missing data in my genotype data

What should I do?

Thank you

**Comment by YinLiLin** [comment]
Hi, this issue has been fixed in the latest version of rMVP on GitHub, please use 'devtools' package to install it and try again.

**Comment by igm11-aa** [comment]
Ive tried it, it resolve my problem. Thank you for your help
