### ISSUE TITLE
cite MVP

### ISSUE THREAD

**Issue by qgao2** [xiaolei-lab/rMVP#19]
Hi Xiaolei,
I am wondering what's the best way to cite MVP in my manuscript. Thanks!

**Comment by XiaoleiLiuBio** [comment]
which method you used?

**Comment by XiaoleiLiuBio** [comment]
I have replied to you one week ago through email, but didn't see any response. Sorry about that.

**Comment by qgao2** [comment]
sorry about that, something wrong with my mailbox. I used FarmCPU for sure
in the paper, and maybe MLM too. Thanks!

**Comment by XiaoleiLiuBio** [comment]
Please cite FarmCPU paper (Liu et.al, 2016, PLoS Genetic.) and Xiang Zhou's GEMMA paper for MLM (Zhou et.al, 2012, Nature Genetic.). I will let you know when MVP paper published

**Comment by XiaoleiLiuBio** [comment]
Thank you for using MVP. Below please find the citation.
Yin L, Zhang H, Tang Z, Xu J, Yin D, Zhang Z, Yuan X, Zhu M, Zhao S, Li X et al. 2020. rMVP: A Memory-efficient, Visualization-enhanced, and Parallel-accelerated tool for Genome-Wide Association Study. bioRxiv doi:10.1101/2020.08.20.258491
