### ISSUE TITLE
cannot install the rMVP package

### ISSUE THREAD

**Issue by yuluc** [xiaolei-lab/rMVP#38]
I tried the two methods you write on GitHub but both of them failed.

> devtools::install_github("xiaoleiLiubio/rMVP@0.99.14.1")
Downloading GitHub repo xiaoleiLiubio/rMVP@0.99.14.1
Error: Failed to install 'rMVP' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

> install.packages("rMVP_0.99.14.1.tar.gz", repos=NULL)
Warning: invalid package ‘rMVP_0.99.14.1.tar.gz’
Error: ERROR: no packages specified

**Comment by hyacz** [comment]
1. Some C++ code is included in rMVP to improve computational efficiency, so you need to compile C++ tools. If you use Windows, RTools can be found [here](https://cran.r-project.org/bin/windows/Rtools/). Mac needs CRAN's clang and gfortran, which can be downloaded from [here](https://cran.r-project.org/bin/macosx/tools/). Linux usually includes the necessary C++ compiler tools, and if you don't have one, please contact your server administrator.

2. This is an offline installation. You must correctly indicate the path to the local package. The package can be downloaded from the Release page.

**Comment by yuluc** [comment]
Thank you for your quick response! 
I installed the clang and gfortran but I still cannot install the package successfully.
> devtools::install_github("xiaoleiLiubio/rMVP@0.99.14.1")
Downloading GitHub repo xiaoleiLiubio/rMVP@0.99.14.1
Your system is ready to build packages!
✔  checking for file ‘/private/var/folders/z8/41981c953kb8f2fk__vh8w500000gn/T/RtmpR5a9pR/remotes1c47ccf14e4/XiaoleiLiuBio-rMVP-c28e333/DESCRIPTION’ ...
─  preparing ‘rMVP’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘rMVP/vignettes’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘rMVP_0.99.14.1.tar.gz’
   
* installing *source* package ‘rMVP’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppProgress/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/bigmemory/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘rMVP’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rMVP’
Error: Failed to install 'rMVP' from GitHub:
  (converted from warning) installation of package ‘/var/folders/z8/41981c953kb8f2fk__vh8w500000gn/T//RtmpR5a9pR/file1c430b118f0/rMVP_0.99.14.1.tar.gz’ had non-zero exit status

**Comment by Gill85** [comment]
Hi, many thanks for building a great Script. I have an issue as I cant install rMVP and found error below..

install.packages("https://mran.microsoft.com/download/")
Installing package into ‘C:/Users/THINK/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘https://mran.microsoft.com/download/’ is not available (for R version 3.5.1)
> install.packages("https://cran.r-project.org/bin/windows/testing/rtools40.html")
Installing package into ‘C:/Users/THINK/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘https://cran.r-project.org/bin/windows/testing/rtools40.html’ is not available (for R version 3.5.1). 

I have even tried with latest version 3.6.1 but still have the same issue. 

Sincerely

Gill

**Comment by XiaoleiLiuBio** [comment]
Hi Gill,

Thank you for trying rMVP. Please install the latest R version 3.6.1 and install rMVP by the following script:

install.packages(“rMVP”)

For the downloads of Microsoft R Open and Rtools, you can go to the related website. Please let me know if you have any other problems.

Cheers,
Xiaolei


---------------- 

---------- Origin message ----------
>From："Rafaqat Ali Gill" <notifications@github.com>
>To："xiaolei-lab/rMVP" <rMVP@noreply.github.com>
>Subject：Re: [xiaolei-lab/rMVP] cannot install the rMVP package (#38)
>Date：2019-10-20 23:07:17Hi, many thanks for building a great Script. I have an issue as I cant install rMVP and found error below..

install.packages("https://mran.microsoft.com/download/")
Installing package into ‘C:/Users/THINK/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘https://mran.microsoft.com/download/’ is not available (for R version 3.5.1)
> install.packages("https://cran.r-project.org/bin/windows/testing/rtools40.html")
Installing package into ‘C:/Users/THINK/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘https://cran.r-project.org/bin/windows/testing/rtools40.html’ is not available (for R version 3.5.1).

I have even tried with latest version 3.6.1 but still have the same issue.

Sincerely

Gill

**Comment by xuefenfei712** [comment]
##install error
I tried to install rMVP in Linux system, but I got the problem showed below, I tried many ways in including  modify Makeconf file of R. Thankyou for your help!

* installing to library ?home/bin/R/x86_64-pc-linux-gnu-library/4.0?
* installing *source* package 鈘MVP?...
** package 鈘MVP?successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error: C++11 standard requested but CXX11 is not defined
* removing ?home/bin/R/x86_64-pc-linux-gnu-library/4.0/rMVP?

**Comment by XiaoleiLiuBio** [comment]
Please update your R to 3.6.2+ and install rMVP by install.packages("rMVP")

**Comment by xuefenfei712** [comment]
Thankyou for your reply, my R version is R-4.0, the latest version.

**Comment by XiaoleiLiuBio** [comment]
Does it work? If not, please also try to update the GCC in your computer.

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
