### ISSUE TITLE
set color for SNP density figure

### ISSUE THREAD

**Issue by shenweima** [xiaolei-lab/rMVP#41]
How to change grey color to white color?
![image](https://user-images.githubusercontent.com/8536868/65810967-27eac080-e1e4-11e9-8c1a-8f8d803bcaf4.png)

**Comment by YinLiLin** [comment]
sorry, the color for region without SNPs can't be changed by default, unless you tweak the scripts of rMVP package before a local installation.

**Comment by shenweima** [comment]
OK.  I exported the picture in ppt format and then changed it.

![image](https://user-images.githubusercontent.com/8536868/65824458-21b81b00-e29c-11e9-8676-0b2e5521cce2.png)

**Comment by YinLiLin** [comment]
Amazing! :thumbsup::thumbsup::thumbsup:

**Comment by pxthxk** [comment]
> sorry, the color for region without SNPs can't be changed by default, unless you tweak the scripts of rMVP package before a local installation.

Can you help locate that snippet?

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
