### ISSUE TITLE
Do you plan to have Julia package?

### ISSUE THREAD

**Issue by zhaotianjing** [xiaolei-lab/rMVP#42]
Hi,

rMVP is a very excellent package and I was wondering whether I can wrap your R package into a Julia package. Then Julia users are able to use your package.

Thanks,

**Comment by YinLiLin** [comment]
Hi,

Thank you for your interest in our package, we haven't planed to warp it to another programming platform yet, but you are definitely welcomed to try it, and we are pleasure to assist if you have any trouble within your processes.

regards,
Lilin

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
