### ISSUE TITLE
MVP.Report   all traits in separated axes

### ISSUE THREAD

**Issue by shenweima** [xiaolei-lab/rMVP#45]
Hi. How to set parameter for showing all traits in separated axes ?
![image](https://user-images.githubusercontent.com/8536868/71759198-629b7d80-2ee4-11ea-975b-09e1777bad27.png)

**Comment by YinLiLin** [comment]
Hi,

rMVP output both separated and united (as you showed above) Manhattan plot, please check all output files in your work directory, the single Manhattan plot for each trait is saved in separated files.

Cheers

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
