### ISSUE TITLE
could not find function "MVP.Data"

### ISSUE THREAD

**Issue by rupesht** [xiaolei-lab/rMVP#51]
Unable execute the code getting error as
Error in MVP.Data(fileHMP = "HapMapwildsoy.hmp.txt", filePhe = "Pheno_269.txt",  :    could not find function "MVP.Data"

**Comment by hyacz** [comment]
You need to execute `library(rMVP)` before using the functions in rMVP

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
