### ISSUE TITLE
permutation quantile

### ISSUE THREAD

**Issue by micwij** [xiaolei-lab/rMVP#52]
Hi,

I am new to GitHub, so please excuse me if my question is not issued in a proper way.

I have a question regarding the permutation threshold. If I understand it correctly, the 95% quantile of the p-values vector is used as a significance threshold and I found that to be relatively high or maybe not stringent enough (see below an example with 200 permutations).

![Rectangular-Manhattan m_2 MLM_dom](https://user-images.githubusercontent.com/73993884/98234166-55b24500-1f60-11eb-8fb1-3d4e26df3aa6.jpg)

The authors of this paper (https://onlinelibrary.wiley.com/doi/full/10.1111/tpj.14659) used a 95% quantile not of the p-value itself but the -log10(p) value.

![image](https://user-images.githubusercontent.com/73993884/98234275-80040280-1f60-11eb-8b1c-1efb40e29b14.png)
Figure 5: Arouisse, B., Korte, A., van Eeuwijk, F., & Kruijer, W. (2020). Imputation of 3 million SNPs in the Arabidopsis regional mapping population. The Plant Journal, 102(4), 872–882. https://doi.org/10.1111/tpj.14659
(this is a different trait as the one I tested, but the experiment is in the same species, with a similar amount of genotypes as I used and I obtained the markers from their imputation)

Following that approach I was wondering whether this would correspond to a 5% quantile if the p-value itself is used. Maybe this is a matter of preference, but I was thinking that having a relatively stringent p-value, while still detecting significant results would be a good trade-off between type I and II errors. Maybe I am understanding the math/statistics behind it incorrectly, but I would appreciate it if you could give a short comment.
Thanks a lot in advance!

**Comment by XiaoleiLiuBio** [comment]
Thank you for your question. Compared with the Bonferroni cutoff, the threshold derived from the permutation test maybe a good choice to reduce both false positives and false negatives. And, to use either p-value or -log (p-value) would give the same threshold. Which method did you use in the figure that you have shown at the beginning of your comment? GLM?

**Comment by micwij** [comment]
Thanks for the quick reply.

I made a short example in R, which maybe explains what I mean. Assuming 200 permutations create a vector of normally distributed p-values.

> x <- rnorm(200, mean = 0.0005, sd = 0.0001)

If one then takes the 95% quantile of the - log(p-value) you get the following value (this would be the approach as the authors used I cited)

> quantile(-log10(x), 0.95)
     95% 
3.484976 

If one takes the -log(p-value) first and takes the 95% quantile this results in a lower value.

> -log10(quantile(x, 0.95))
     95% 
3.186002

However, if we take the 5% quantile, this is much closer to the first approach:

> -log10(quantile(x, 0.05))
      5% 
3.484975 

I guess the difference could be even stronger if the generated p-values resulting from the permutation are not normally distributed.
Sorry, maybe I understood it wrong or it is just a matter of perspective, which quantile to take, but I was just wondering whether this could be sensible.

The method I used is MLM.

**Comment by XiaoleiLiuBio** [comment]
Both p-value and -log10(p-value) should be sorted first, one is from big to small while the other one is from small to big.

**Comment by micwij** [comment]
Okay. Now I understand. Thanks a lot for the explanation!

**Comment by XiaoleiLiuBio** [comment]
You are welcome. Thank you for using rMVP and thanks for your nice question.

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.

**Comment by jrod55** [comment]
Hi,

Following up on the topic of permutations, when rMVP calculates the permutation threshold, It appears that during the permutation step rMVP is using the standard error distribution instead of p-values? I've copied the chunk of code from MVP.R where this step is occurring below. The results from MVP.GLM should be Effect, Standard error, p-value? So shouldn't the column being subset be the third instead of the second column (in the bolded line below)?

if(permutation.threshold){
        # set.seed(12345)
        i=1
        for(i in 1:permutation.rep){
            index = 1:nrow(phe)
            index.shuffle = sample(index,length(index),replace=FALSE)
            myY.shuffle = phe
            myY.shuffle[,2] = myY.shuffle[index.shuffle,2]
            #GWAS using t.test...
            myPermutation = MVP.GLM(phe=myY.shuffle[,c(1,2)], geno=geno, cpu=ncpus)
            **pvalue = min(myPermutation[,2],na.rm=TRUE)**
            if(i==1){
                    pvalue.final=pvalue
               }else{
                    pvalue.final=c(pvalue.final,pvalue)
            }
        }#end of permutation.rep
        permutation.cutoff = sort(pvalue.final)[ceiling(permutation.rep*0.05)]
        threshold = permutation.cutoff * m
    }

Thank you in advance!
