### ISSUE TITLE
Changing marker size  for bonferoni correction

### ISSUE THREAD

**Issue by mtross2** [xiaolei-lab/rMVP#54]
Hi,

I'm calculated the number of effective SNPs and was wondering how I would be able to change marker size to this value so that I can have a corrected Bonferroni threshold according to the number of effective SNPs. How do I change that in rMVP? I tried doing  threshold = 0.05/effective size but that seems to inflate the threshold value even more. Any suggestions would be appreciated!

**Comment by hyacz** [comment]
Thank you for using rMVP. Actually, the threshold is equal to `-log10(threshold/n_marker)`. The number of markers will be automatically counted and used for Bonferroni correction. If you really want to modify it, you can set threshold = 0.05 * n_marker_old / n_marker_new.

**Comment by ramendra-sarma** [comment]
> Thank you for using rMVP. Actually, the threshold is equal to `-log10(threshold/n_marker)`. The number of markers will be automatically counted and used for Bonferroni correction. If you really want to modify it, you can set threshold = 0.05 * n_marker_old / n_marker_new.

What code shouls I use as " threshold = 0.05 * n_marker_old / n_marker_new" generate error
