### ISSUE TITLE
What's the change of 1.0.3 to 1.0.4?

### ISSUE THREAD

**Issue by Jiny000** [xiaolei-lab/rMVP#55]
Hi,
I very love your package.However,I found the result of rMVP v1.0.3 and v1.0.4 is different.I wonder why the result is obviously different with the same r script as well as  data.I can't find the update information in github or cran.
![Area FarmCPU QQplot 2](https://user-images.githubusercontent.com/56862503/100329499-afaaa580-3008-11eb-9fe6-aa64cde23404.jpg)
Above is the result of v1.0.3
![Area FarmCPU QQplot 1](https://user-images.githubusercontent.com/56862503/100329486-ad484b80-3008-11eb-857d-65c67f9ee8dc.jpg)
Above is the result of v1.0.4

By the way,I want to set the cut off as a constant,such as -log10(p)=5,how can I make it in MVP?
Sincerely,
Jingyao

**Comment by XiaoleiLiuBio** [comment]
rMVP 1.0.4
@hyacz hyacz released this on Sep 1 · 7 commits to master since this release

Enhance
adding Dockerfile
update README.md
update c++ for kinship computation
Bugfix
stop if hapmap major is not in 'ATGC'
fixed bug of skipping SNPs when converting vcf/hapmap to mvp genotype file format.

**Comment by XiaoleiLiuBio** [comment]
Thank you for reporting the issue. I think the differences may be caused by the SNPs that skipped by the previous version.
