### ISSUE TITLE
Error: Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by TinaNeik339** [xiaolei-lab/rMVP#61]
Hi, I'm using MacOS Big Sur version 11.2.1 to run rMVP but encountered this problem:

> devtools::install_github("xiaolei-lab/rMVP")
Downloading GitHub repo xiaolei-lab/rMVP@master
Error: Could not find tools necessary to compile a package

I have installed additional build tools from the apple website (Xcode Beta latest version, is this necessary?) but still the error message appears. 

What else should I download? Any help is appreciated. 

Thank you in advance.

**Comment by XiaoleiLiuBio** [comment]
Hi there, Xcode and gfortran are required for R 4.0, clang and gfortran are required for R 3.x (https://cran.r-project.org/bin/macosx/tools/).
