### ISSUE TITLE
MVP pvalue permutation returned

### ISSUE THREAD

**Issue by jrod55** [xiaolei-lab/rMVP#64]
Hi,

When rMVP calculates the permutation threshold, It appears that during the permutation step rMVP is using the standard error distribution instead of p-values? I've copied the chunk of code from MVP.R where this step is occurring below. The results from MVP.GLM should be Effect, Standard error, p-value? So shouldn't the column being subset be the third instead of the second column (in the bolded line below)?

if(permutation.threshold){
i=1
for(i in 1:permutation.rep){
index = 1:nrow(phe)
index.shuffle = sample(index,length(index),replace=FALSE)
myY.shuffle = phe
myY.shuffle[,2] = myY.shuffle[index.shuffle,2]
#GWAS using t.test...
myPermutation = MVP.GLM(phe=myY.shuffle[,c(1,2)], geno=geno, cpu=ncpus)
**pvalue = min(myPermutation[,2],na.rm=TRUE)**
if(i==1){
pvalue.final=pvalue
}else{
pvalue.final=c(pvalue.final,pvalue)
}
}#end of permutation.rep
permutation.cutoff = sort(pvalue.final)[ceiling(permutation.rep*0.05)]
threshold = permutation.cutoff * m
}

Thank you in advance!

**Comment by hyacz** [comment]
Hi, Jonas

Thanks for your feedback, it is really wrong here, it should be
```
pvalue = min(myPermutation[,3],na.rm=TRUE)
```
We fixed this problem in the recent commit 07d2113182bdffcf2eefb63dd04892cb57c2dc33, and we will submit version 1.0.6 to CRAN to fix this bug.

Finally, thank you for using rMVP, and sorry for the trouble caused by the bug.

**Comment by jrod55** [comment]
No worries, thanks for the quick reply and thank you for the excellent package.
