### ISSUE TITLE
Can't install rmVP

### ISSUE THREAD

**Issue by TinaNeik339** [xiaolei-lab/rMVP#68]
Hi, 

I tried installing rMVP using the manual given, here is the error:

> devtools::install_github("xiaolei-lab/rMVP")
Downloading GitHub repo xiaolei-lab/rMVP@HEAD
Error: Failed to install 'rMVP' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

I am using MacOS Big Sur 11.2.1, and have installed Xcode 11.7 Beta and Command lines for Xcode 12

Still I'm getting the error message above. 

May I know what is the problem?

Thank you for your help.

**Comment by TinaNeik339** [comment]
By the way, forgot to mention that I have also installed clang-8.0 on my Macbook, but can't install rMVP still

**Comment by hyacz** [comment]
You can install macOS binary files directly from CRAN with the following command:
```install.packages("rMVP")```

you can follow the prompts to call `pkgbuild::check_build_tools(debug = TRUE)` for further error troubleshooting. In addition, you can refer to https://cran.r-project.org/bin/macosx/tools to configure your build tools.

**Comment by TinaNeik339** [comment]
Thank you for your help, I managed to install rMVP already.
