### ISSUE TITLE
using multiple cores

### ISSUE THREAD

**Issue by MuBulut** [xiaolei-lab/rMVP#78]
Hi

I have question concerning the ncpus option:
Whenever I start my R-script (on a multi core) machine,
it seems, that there is never more than 1 cpu utilized,
The load is always around 1 with one thread at 100%.

I tried to specify
ncpus=10 and also commenting out the option (which would
mean all cores found should be used, right?), but could
not see any change in behaviour.

Could you please comment on how to make sure (and check),
that more than one cpu is used by rMVP?

**Comment by hyacz** [comment]
I usually check that the scripts are properly parallelized via a monitoring tool (e.g. `top`). can you show me the OS and R version, and the script?

**Comment by MuBulut** [comment]
Top is exactly the tool I used and realized, the load is never more than 1 and only 1 thread seems to be running.
OS: Ubuntu Linux 20.04
R: 4.1.2
---------------
the script:
for(i in 2:length(name)){
  gc() 
    imMVP <- MVP(
    phe=met_all[, c(1,i)],
    geno=genotype,
    map=map,
    K=Kinship,
    #CV.GLM=Covariates,
    CV.MLM=Covariates,
    #CV.FarmCPU=Covariates,
    #nPC.MLM=0,
    priority="speed",
    ncpus=20,
    vc.method="EMMA",
    #maxLoop=10,
    method.bin="EMMA",#"FaST-LMM","EMMA", "static"
    #permutation.threshold=TRUE,
    #permutation.rep=100,
    threshold=0.05,
    method="MLM",
    col=c("steelblue4","cyan3"),
    memo='dom',
    file.output = T
    )

**Comment by hyacz** [comment]
There is a line like this in MVP's log output
```
Number of threads used: <threads>
```
Can you check the number here?

I guess it may be that the OpenMP environment is abnormal or the use of threads is restricted by the system level
