### ISSUE TITLE
表型分布

### ISSUE THREAD

**Issue by MooreZhu** [xiaolei-lab/rMVP#79]
老师，您好！请问作表型分布图的需要的数据是什么，我的数据第一列是id，之后的列是表型，但是在作图的时候报错`Error in hist.default(x = phe[, i], plot = FALSE, breaks = Breaks, xlab = "",  :  'x' 必需是数值`，请问是哪里出了错？

**Comment by YinLiLin** [comment]
检查一下表型是否含有非数字字符
