### ISSUE TITLE
Error in make.names(col.names, unique = TRUE) :    invalid multibyte string at '<ff><fe>I'

### ISSUE THREAD

**Issue by Wyinghao** [xiaolei-lab/rMVP#89]
Hi！When I was testing rMVP, I encountered such an error, I would like to ask what is the cause of the error? My input file is a format converted by plink, as well as a two-column phenotypic data (the first column is ID, and the second column is phenotypic value)
> MVP.Data(filePhe="max_phe.txt",fileBed="test",out="test1")
Preparing data for MVP...
Reading file...
Preparation for MAP data is done within 2m10s 
inds: 165	markers:13221342
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Preparation for GENOTYPE data is done within 12m58s 
Error in make.names(col.names, unique = TRUE) : 
  invalid multibyte string at '<ff><fe>I'
In addition: Warning messages:
1: In MVP.Data.Map(bim_file, out = out, cols = c(2, 1, 4, 6, 5), header = FALSE) :
  WARNING: SNP is not unique and has been automatically renamed.
2: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 1 appears to contain embedded nulls
3: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 2 appears to contain embedded nulls
4: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 3 appears to contain embedded nulls
5: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 4 appears to contain embedded nulls
6: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 5 appears to contain embedded nulls

**Comment by Wyinghao** [comment]
I seem to have found the reason, it is because my phenotype file is in Windows format upload server is incompatible with Linux format, using dos2unix your_phe.file to solve the problem

**Comment by Wyinghao** [comment]
> Hi！When I was testing rMVP, I encountered such an error, I would like to ask what is the cause of the error? My input file is a format converted by plink, as well as a two-column phenotypic data (the first column is ID, and the second column is phenotypic value)
> 
> > MVP.Data(filePhe="max_phe.txt",fileBed="test",out="test1")
> > Preparing data for MVP...
> > Reading file...
> > Preparation for MAP data is done within 2m10s
> > inds: 165	markers:13221342
> > 0%   10   20   30   40   50   60   70   80   90   100%
> > [----|----|----|----|----|----|----|----|----|----|
> > **************************************************|
> > Preparation for GENOTYPE data is done within 12m58s
> > Error in make.names(col.names, unique = TRUE) :
> > invalid multibyte string at 'I'
> > In addition: Warning messages:
> > 1: In MVP.Data.Map(bim_file, out = out, cols = c(2, 1, 4, 6, 5), header = FALSE) :
> > WARNING: SNP is not unique and has been automatically renamed.
> > 2: In read.table(file = file, header = header, sep = sep, quote = quote,  :
> > line 1 appears to contain embedded nulls
> > 3: In read.table(file = file, header = header, sep = sep, quote = quote,  :
> > line 2 appears to contain embedded nulls
> > 4: In read.table(file = file, header = header, sep = sep, quote = quote,  :
> > line 3 appears to contain embedded nulls
> > 5: In read.table(file = file, header = header, sep = sep, quote = quote,  :
> > line 4 appears to contain embedded nulls
> > 6: In read.table(file = file, header = header, sep = sep, quote = quote,  :
> > line 5 appears to contain embedded nulls

I seem to have found the reason, it is because my phenotype file is in Windows format upload server is incompatible with Linux format, using dos2unix your_phe.file to solve the problem

**Comment by hyacz** [comment]
Thank you for using our software and for bringing the issue to our attention. We appreciate your feedback and are glad to hear that you were able to resolve the issue on your own.

As per your request, I have closed the issue. If you have any further questions or concerns, please don’t hesitate to reach out to us. We are always here to help.
